trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'site'
